apiVersion: v1
kind: Service
metadata:
  labels:
    app: resume
  name: resume
spec:
  type: NodePort
  ports:
  - name: "resume-service"
    port: 80
    targetPort: 5000
    nodePort: 31000
  selector:
    app: vote
  
