apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume
  name: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: resumecr.azurecr.io/resumeapp:32
        name: resume
        ports:
        - containerPort: 5000
          name: resume
      imagePullSecrets:
      - name: acr-secret
