apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resume-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resume
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale if CPU usage exceeds 50%

