apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume
  name: resume
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: resumecr.azurecr.io/resumeapp:39
        name: resume
        ports:
        - containerPort: 80
          name: resume
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"       # 100 milliCPU
            memory: "128Mi"   # 128 MiB memory
          limits:
            cpu: "500m"       # 500 milliCPU
            memory: "256Mi"   # 256 MiB memory
      imagePullSecrets:
      - name: acr-secret
